### ISSUE TITLE
Some core TODO 

### ISSUE THREAD

**Issue by blinkinglight** [streamingriver/river#1]
Need tool to solve problem with master playlists.

- [ ]  New frontend ( maybe angular )
- [ ]  New backend ( api first, backend )
- [ ] Maybe atlas go to handle database migrations
- [ ] Tool to handle various types of urls ( like extract link from master or chanels playlist etc. ) 
- [ ] Bash or ansible scripts to checkout repo, install nomad and consul maybe ask customer some input ( like domain ) 
- [ ] Script to run nomad jobs ( install / update ) 
- [ ] Update system ( with nomad it becomes more simple )
- [ ] New reverse proxy version to handle ACL on urls from STB's/vlc or other frontends 
- [ ] Implement ffmpeg on demand ( to save traffic if noone is watching ) 
- [ ] Other tools as we go
